/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApiCatalogRouteImport } from './routes/api.catalog'
import { Route as ApiDealsRouteImport } from './routes/api.deals'
import { Route as ApiRankingsRouteImport } from './routes/api.rankings'
import { Route as ApiReleasesRouteImport } from './routes/api.releases'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as DeveloperDeveloperRouteImport } from './routes/developer.$developer'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesGameRouteImport } from './routes/games.$game'
import { Route as PublisherIndexRouteImport } from './routes/publisher.index'
import { Route as PublisherPublisherRouteImport } from './routes/publisher.$publisher'
import { Route as PublishersIndexRouteImport } from './routes/publishers.index'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as RankingsPeakRouteImport } from './routes/rankings.peak'
import { Route as ReleasesIndexRouteImport } from './routes/releases.index'
import { Route as ReleasesWeekRouteImport } from './routes/releases.$week'
import { Route as ApiPlayersHistoryRouteImport } from './routes/api.players.history'
import { Route as ApiPricesHistoryRouteImport } from './routes/api.prices.history'
import { Route as GamesGameChildRouteImport } from './routes/games.$game_.$child'
import { Route as ApiGamesAppidDetailRouteImport } from './routes/api.games.$appid.detail'
import { Route as ApiGamesAppidOverviewRouteImport } from './routes/api.games.$appid.overview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealsRoute = ApiDealsRouteImport.update({
  id: '/api/deals',
  path: '/api/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRankingsRoute = ApiRankingsRouteImport.update({
  id: '/api/rankings',
  path: '/api/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesRoute = ApiReleasesRouteImport.update({
  id: '/api/releases',
  path: '/api/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDeveloperRoute = DeveloperDeveloperRouteImport.update({
  id: '/developer/$developer',
  path: '/developer/$developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameRoute = GamesGameRouteImport.update({
  id: '/games/$game',
  path: '/games/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherIndexRoute = PublisherIndexRouteImport.update({
  id: '/publisher/',
  path: '/publisher/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPublisherRoute = PublisherPublisherRouteImport.update({
  id: '/publisher/$publisher',
  path: '/publisher/$publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishersIndexRoute = PublishersIndexRouteImport.update({
  id: '/publishers/',
  path: '/publishers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPeakRoute = RankingsPeakRouteImport.update({
  id: '/rankings/peak',
  path: '/rankings/peak',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesWeekRoute = ReleasesWeekRouteImport.update({
  id: '/releases/$week',
  path: '/releases/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersHistoryRoute = ApiPlayersHistoryRouteImport.update({
  id: '/api/players/history',
  path: '/api/players/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesHistoryRoute = ApiPricesHistoryRouteImport.update({
  id: '/api/prices/history',
  path: '/api/prices/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameChildRoute = GamesGameChildRouteImport.update({
  id: '/games/$game_/$child',
  path: '/games/$game/$child',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesAppidDetailRoute = ApiGamesAppidDetailRouteImport.update({
  id: '/api/games/$appid/detail',
  path: '/api/games/$appid/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesAppidOverviewRoute = ApiGamesAppidOverviewRouteImport.update({
  id: '/api/games/$appid/overview',
  path: '/api/games/$appid/overview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/deals': typeof ApiDealsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/search': typeof ApiSearchRoute
  '/developer/$developer': typeof DeveloperDeveloperRoute
  '/games/$game': typeof GamesGameRoute
  '/publisher/$publisher': typeof PublisherPublisherRoute
  '/rankings/peak': typeof RankingsPeakRoute
  '/releases/$week': typeof ReleasesWeekRoute
  '/developers/': typeof DevelopersIndexRoute
  '/games/': typeof GamesIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/api/players/history': typeof ApiPlayersHistoryRoute
  '/api/prices/history': typeof ApiPricesHistoryRoute
  '/games/$game/$child': typeof GamesGameChildRoute
  '/api/games/$appid/detail': typeof ApiGamesAppidDetailRoute
  '/api/games/$appid/overview': typeof ApiGamesAppidOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/deals': typeof ApiDealsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/search': typeof ApiSearchRoute
  '/developer/$developer': typeof DeveloperDeveloperRoute
  '/games/$game': typeof GamesGameRoute
  '/publisher/$publisher': typeof PublisherPublisherRoute
  '/rankings/peak': typeof RankingsPeakRoute
  '/releases/$week': typeof ReleasesWeekRoute
  '/developers': typeof DevelopersIndexRoute
  '/games': typeof GamesIndexRoute
  '/publisher': typeof PublisherIndexRoute
  '/publishers': typeof PublishersIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/api/players/history': typeof ApiPlayersHistoryRoute
  '/api/prices/history': typeof ApiPricesHistoryRoute
  '/games/$game/$child': typeof GamesGameChildRoute
  '/api/games/$appid/detail': typeof ApiGamesAppidDetailRoute
  '/api/games/$appid/overview': typeof ApiGamesAppidOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/deals': typeof ApiDealsRoute
  '/api/rankings': typeof ApiRankingsRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/search': typeof ApiSearchRoute
  '/developer/$developer': typeof DeveloperDeveloperRoute
  '/games/$game': typeof GamesGameRoute
  '/publisher/$publisher': typeof PublisherPublisherRoute
  '/rankings/peak': typeof RankingsPeakRoute
  '/releases/$week': typeof ReleasesWeekRoute
  '/developers/': typeof DevelopersIndexRoute
  '/games/': typeof GamesIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/api/players/history': typeof ApiPlayersHistoryRoute
  '/api/prices/history': typeof ApiPricesHistoryRoute
  '/games/$game_/$child': typeof GamesGameChildRoute
  '/api/games/$appid/detail': typeof ApiGamesAppidDetailRoute
  '/api/games/$appid/overview': typeof ApiGamesAppidOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deals'
    | '/privacy'
    | '/search'
    | '/api/catalog'
    | '/api/deals'
    | '/api/rankings'
    | '/api/releases'
    | '/api/search'
    | '/developer/$developer'
    | '/games/$game'
    | '/publisher/$publisher'
    | '/rankings/peak'
    | '/releases/$week'
    | '/developers/'
    | '/games/'
    | '/publisher/'
    | '/publishers/'
    | '/rankings/'
    | '/releases/'
    | '/api/players/history'
    | '/api/prices/history'
    | '/games/$game/$child'
    | '/api/games/$appid/detail'
    | '/api/games/$appid/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deals'
    | '/privacy'
    | '/search'
    | '/api/catalog'
    | '/api/deals'
    | '/api/rankings'
    | '/api/releases'
    | '/api/search'
    | '/developer/$developer'
    | '/games/$game'
    | '/publisher/$publisher'
    | '/rankings/peak'
    | '/releases/$week'
    | '/developers'
    | '/games'
    | '/publisher'
    | '/publishers'
    | '/rankings'
    | '/releases'
    | '/api/players/history'
    | '/api/prices/history'
    | '/games/$game/$child'
    | '/api/games/$appid/detail'
    | '/api/games/$appid/overview'
  id:
    | '__root__'
    | '/'
    | '/deals'
    | '/privacy'
    | '/search'
    | '/api/catalog'
    | '/api/deals'
    | '/api/rankings'
    | '/api/releases'
    | '/api/search'
    | '/developer/$developer'
    | '/games/$game'
    | '/publisher/$publisher'
    | '/rankings/peak'
    | '/releases/$week'
    | '/developers/'
    | '/games/'
    | '/publisher/'
    | '/publishers/'
    | '/rankings/'
    | '/releases/'
    | '/api/players/history'
    | '/api/prices/history'
    | '/games/$game_/$child'
    | '/api/games/$appid/detail'
    | '/api/games/$appid/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealsRoute: typeof DealsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiDealsRoute: typeof ApiDealsRoute
  ApiRankingsRoute: typeof ApiRankingsRoute
  ApiReleasesRoute: typeof ApiReleasesRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DeveloperDeveloperRoute: typeof DeveloperDeveloperRoute
  GamesGameRoute: typeof GamesGameRoute
  PublisherPublisherRoute: typeof PublisherPublisherRoute
  RankingsPeakRoute: typeof RankingsPeakRoute
  ReleasesWeekRoute: typeof ReleasesWeekRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PublisherIndexRoute: typeof PublisherIndexRoute
  PublishersIndexRoute: typeof PublishersIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  ApiPlayersHistoryRoute: typeof ApiPlayersHistoryRoute
  ApiPricesHistoryRoute: typeof ApiPricesHistoryRoute
  GamesGameChildRoute: typeof GamesGameChildRoute
  ApiGamesAppidDetailRoute: typeof ApiGamesAppidDetailRoute
  ApiGamesAppidOverviewRoute: typeof ApiGamesAppidOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deals': {
      id: '/api/deals'
      path: '/api/deals'
      fullPath: '/api/deals'
      preLoaderRoute: typeof ApiDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rankings': {
      id: '/api/rankings'
      path: '/api/rankings'
      fullPath: '/api/rankings'
      preLoaderRoute: typeof ApiRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases': {
      id: '/api/releases'
      path: '/api/releases'
      fullPath: '/api/releases'
      preLoaderRoute: typeof ApiReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/$developer': {
      id: '/developer/$developer'
      path: '/developer/$developer'
      fullPath: '/developer/$developer'
      preLoaderRoute: typeof DeveloperDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game': {
      id: '/games/$game'
      path: '/games/$game'
      fullPath: '/games/$game'
      preLoaderRoute: typeof GamesGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/': {
      id: '/publisher/'
      path: '/publisher'
      fullPath: '/publisher/'
      preLoaderRoute: typeof PublisherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/$publisher': {
      id: '/publisher/$publisher'
      path: '/publisher/$publisher'
      fullPath: '/publisher/$publisher'
      preLoaderRoute: typeof PublisherPublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers/': {
      id: '/publishers/'
      path: '/publishers'
      fullPath: '/publishers/'
      preLoaderRoute: typeof PublishersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/peak': {
      id: '/rankings/peak'
      path: '/rankings/peak'
      fullPath: '/rankings/peak'
      preLoaderRoute: typeof RankingsPeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$week': {
      id: '/releases/$week'
      path: '/releases/$week'
      fullPath: '/releases/$week'
      preLoaderRoute: typeof ReleasesWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players/history': {
      id: '/api/players/history'
      path: '/api/players/history'
      fullPath: '/api/players/history'
      preLoaderRoute: typeof ApiPlayersHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices/history': {
      id: '/api/prices/history'
      path: '/api/prices/history'
      fullPath: '/api/prices/history'
      preLoaderRoute: typeof ApiPricesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game_/$child': {
      id: '/games/$game_/$child'
      path: '/games/$game/$child'
      fullPath: '/games/$game/$child'
      preLoaderRoute: typeof GamesGameChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$appid/detail': {
      id: '/api/games/$appid/detail'
      path: '/api/games/$appid/detail'
      fullPath: '/api/games/$appid/detail'
      preLoaderRoute: typeof ApiGamesAppidDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$appid/overview': {
      id: '/api/games/$appid/overview'
      path: '/api/games/$appid/overview'
      fullPath: '/api/games/$appid/overview'
      preLoaderRoute: typeof ApiGamesAppidOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealsRoute: DealsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiDealsRoute: ApiDealsRoute,
  ApiRankingsRoute: ApiRankingsRoute,
  ApiReleasesRoute: ApiReleasesRoute,
  ApiSearchRoute: ApiSearchRoute,
  DeveloperDeveloperRoute: DeveloperDeveloperRoute,
  GamesGameRoute: GamesGameRoute,
  PublisherPublisherRoute: PublisherPublisherRoute,
  RankingsPeakRoute: RankingsPeakRoute,
  ReleasesWeekRoute: ReleasesWeekRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  PublisherIndexRoute: PublisherIndexRoute,
  PublishersIndexRoute: PublishersIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  ApiPlayersHistoryRoute: ApiPlayersHistoryRoute,
  ApiPricesHistoryRoute: ApiPricesHistoryRoute,
  GamesGameChildRoute: GamesGameChildRoute,
  ApiGamesAppidDetailRoute: ApiGamesAppidDetailRoute,
  ApiGamesAppidOverviewRoute: ApiGamesAppidOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
